import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LANDING PAGE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={
            "h-full w-full bg-gradient-to-br from-[#0F2027] via-[#203A43] to-[#2C5364]"
          }
        >
          {children}
        </div>
      </body>
    </html>
  );
}
